name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: true
        
      - name: Install ğŸ”§
        run: npm install

      - name: Build Env Variables
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: npm run build-env-variables

      - name: Save Env Variables
        run: echo TOKEN_GH=${{ secrets.TOKEN_GITHUB }} >> .enver

      - name: Build ğŸ—ï¸
        run: npm run build

      - name: Publish ğŸ“¨
        run: |
          git config --global user.name 'balovbohdan'
          git config --global user.email 'balovbohdan@users.noreply.github.com'
          git add .
          git commit -am "publish"
          git push
