name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: true
        
      - name: Install Dependencies ğŸ”§
        run: npm install

      - name: Build Env Variables âœ‚ï¸
        run: |
          echo TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }} >> .env
          npm run build-env-variables

      - name: Build ğŸ—ï¸
        run: npm run build

      - name: Remove Source Files ğŸ”§
        run: rm -rf !(docs)

      - name: Publish ğŸ“¨
        run: |
          git config --global user.name 'balovbohdan'
          git config --global user.email 'balovbohdan@users.noreply.github.com'
          git add .
          git checkout github-page
          git commit -am "publish"
          git push
